### PR TITLE
Faster dispatch

### PR DESCRIPTION
**Pull request by markshannon**
For review purposes. Please don't merge.

This should :crossed_fingers: result in MSVC producing a dispatch sequence as efficient as GCC with computed gotos.
This (in theory) works by:
* Creating an exhaustive set of switch targets and limiting the opcode to a single byte, so there is no need for any range checking.
* Generating unique code for each target, so the compiler can't merge them.
* Removing all code between the fetch/decode and dispatch, allowing the compiler to merge the goto with the computed jump.

The dispatch code should end up looking something like:
```asm
        movzx   ecx, WORD PTR [edi]
        add     edi, 2
        mov     esi, ecx
        movzx   eax, cl
        shr     esi, 8
        jmp     TABLE[eax*4]
```
The important thing is that there is a computed jump at the end of the instruction code.

### CODE REVIEW

**Comment by markshannon** [comment]
If this works, we can remove all the `PREDICT` macros as well.

**Comment by gvanrossum** [comment]
See email I sent with Disassembly.txt

**Comment by gvanrossum** [comment]
Here's the disassembly for all of `_PyEval_EvalFrameDefault()` with some extra stuff before and after it.

[Disassembly.txt](https://github.com/faster-cpython/cpython/files/6266355/Disassembly.txt)

**Comment by markshannon** [comment]
There still seem to a lot of conditional jumps and even a call in the `DISPATCH()` code.
Do you have `LLTRACE` or `DTRACE` enabled?

**Comment by markshannon** [comment]
Closing this.
I'll make another PR with just the extra opcodes, once https://bugs.python.org/issue43760 is done

**Comment by gvanrossum** [comment]
(And no, I did not have LLTRACE or DTRACE explicitly enabled. Whether
they're enabled by default I have no idea -- if you want me to find out I
can though.)

**Pull request closed without merging**
